# Generated by Django 5.0.4 on 2024-04-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organization', models.CharField(max_length=100)),
                ('sponsor_type', models.CharField(choices=[('yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], default='jismoniy', max_length=100)),
                ('conditions', models.CharField(choices=[('yangi', 'Yangi'), ('madiratsiyada', 'Madiratsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('bekor_qilingan', 'Bekor qilingan')], default='yangi', max_length=20)),
                ('payment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_type', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magister', 'Magister')], default='bakalavr', max_length=100)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='unversity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.unversity'),
        ),
    ]
