# Generated by Django 5.0.4 on 2024-05-03 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_basemodel_sponsor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_data', to='app.sponsor'),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_data', to='app.student'),
        ),
    ]
